# Generated by Django 3.2.21 on 2024-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentAmount',
            fields=[
                ('rent_amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'rent_amount',
                'managed': False,
            },
        ),
    ]
