# Generated by Django 3.2.21 on 2024-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('size', models.CharField(max_length=45)),
                ('rent_amount', models.FloatField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cycle',
                'managed': False,
            },
        ),
    ]
