# Generated by Django 3.2.21 on 2024-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=45)),
                ('charge', models.IntegerField()),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
