# Generated by Django 3.2.21 on 2024-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'track',
                'managed': False,
            },
        ),
    ]
